/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateChallange = /* GraphQL */ `
  subscription OnCreateChallange {
    onCreateChallange {
      id
      phase
      status
      coName
      coTitle
      coEmail
      coPhone
      coOptIn
      orgaTitle
      orgaCity
      orgaMission
      orgaWebsite
      orgaDate
      chaStatem
      chaDes
      chaStak
      chaBac
      chaSup
      leadSup
      critOfSuc
      nextStep
      chatitle
      theme
      technology
      repu
      feasibil
      impact
      scalabil
      aligment
      prototype
      score
      type
      comment
      faculty
      prof
      matchEmail
      numberOfT
      numberOfS
      startDate
      endDate
      cohort
      milestone
      publURL
      gitHubURL
      publDate
      timestamp
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onUpdateChallange = /* GraphQL */ `
  subscription OnUpdateChallange {
    onUpdateChallange {
      id
      phase
      status
      coName
      coTitle
      coEmail
      coPhone
      coOptIn
      orgaTitle
      orgaCity
      orgaMission
      orgaWebsite
      orgaDate
      chaStatem
      chaDes
      chaStak
      chaBac
      chaSup
      leadSup
      critOfSuc
      nextStep
      chatitle
      theme
      technology
      repu
      feasibil
      impact
      scalabil
      aligment
      prototype
      score
      type
      comment
      faculty
      prof
      matchEmail
      numberOfT
      numberOfS
      startDate
      endDate
      cohort
      milestone
      publURL
      gitHubURL
      publDate
      timestamp
      createdAt
      updatedAt
      owner
    }
  }
`;
export const onDeleteChallange = /* GraphQL */ `
  subscription OnDeleteChallange {
    onDeleteChallange {
      id
      phase
      status
      coName
      coTitle
      coEmail
      coPhone
      coOptIn
      orgaTitle
      orgaCity
      orgaMission
      orgaWebsite
      orgaDate
      chaStatem
      chaDes
      chaStak
      chaBac
      chaSup
      leadSup
      critOfSuc
      nextStep
      chatitle
      theme
      technology
      repu
      feasibil
      impact
      scalabil
      aligment
      prototype
      score
      type
      comment
      faculty
      prof
      matchEmail
      numberOfT
      numberOfS
      startDate
      endDate
      cohort
      milestone
      publURL
      gitHubURL
      publDate
      timestamp
      createdAt
      updatedAt
      owner
    }
  }
`;
